name: Deploy to OCI Kubernetes

on:
  workflow_run:
    workflows: [ "Build Docker Images" ]
    types: [ completed ]
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy Portfolio Helm Chart
        uses: 'deliverybot/helm@v1'
        with:
          release: 'portfolio'
          namespace: 'portfolio'
          chart: './charts/portfolio'
          # token: '${{ github.token }}'
        env:
          KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'
