name: Deploy to OCI Kubernetes

on:
  workflow_run:
    workflows: [ "Build Docker Images" ]
    types: [ completed ]
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: azure/setup-helm@v4.3.0
        id: install

      - uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}
          context: context-c6vtj65lwcq

      - name: Install oci command
        uses: oracle-actions/run-oci-cli-command@v1.3.2
        with:
          command: --version

      - run: oci --version


      - run: |
          helm upgrade --install --namespace portfolio portfolio ./charts/portfolio
