name: Deploy to OCI Kubernetes

on:
  workflow_run:
    workflows: [ "Build Docker Images" ]
    types: [ completed ]
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: azure/setup-helm@v4.3.0
        id: install

      - name: Install oci command and setup kubeconfig
        uses: oracle-actions/run-oci-cli-command@v1.3.2
        with:
          command: ce cluster create-kubeconfig --cluster-id ${{ secrets.OCI_CLUSTER_ID }} --file $HOME/.kube/config --region eu-madrid-1 --token-version 2.0.0  --kube-endpoint PUBLIC_ENDPOINT

      - name: Deploy portfolio Helm Chart
        run: |
          helm upgrade --install --namespace portfolio portfolio ./charts/portfolio
