name: Deploy to OCI Kubernetes

on:
  workflow_run:
    workflows: [ "Build Docker Images" ]
    types: [ completed ]
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: azure/setup-helm@v4.3.0
        id: install
